FROM gcc
WORKDIR /build
RUN chmod 777 /build

RUN apt-get update
RUN apt-get -y install sudo lsb-release

RUN curl -L -O https://github.com/zeutro/openabe/releases/download/v1.0/libopenabe-1.0.0-src.tar.gz
RUN tar xvzf libopenabe-1.0.0-src.tar.gz

WORKDIR /build/libopenabe-1.0.0/
ENV ZROOT /build/libopenabe-1.0.0/
RUN ./deps/install_pkgs.sh

RUN make

COPY . /build/sccplib
WORKDIR /build/sccplib

RUN make
